on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build using node JS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci --legacy-peer-deps
      - run: npm run build
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          protocol: ftps
          local-dir: ./build/
          server-dir: /service.reisinger.pictures/
